# Change these first
owner: evintoh # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: BMS SG
    url: https://sg.bookmyshow.com/
  - name: BMS ID
    url: https://id.bookmyshow.com/
  - name: BMS MY
    url: https://my.bookmyshow.com/
  - name: BMS SG Pos
    url: http://pos-sg.bigtix.io/
  - name: BMS SG Admin
    url: http://admin-sg.bigtix.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/evintoh/upptime/master/assets/bms_logo.svg
  name: BMSSEA
  introTitle: "BMSSEA Status"
  introMessage: This is a status page based on upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
